# Generated by Django 4.2.7 on 2024-03-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_letters_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='letters',
            table='Letters',
        ),
    ]
